on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    container: openfoamplus/of_v1906_centos73
    name: A job to test OpenFOAM
    steps:
    - name: Checkout this
      id: checkout-this
      uses: actions/checkout@v2
    - name: Install Miniconda
      id: install-miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh && sh Miniconda3-py39_4.9.2-Linux-x86_64.sh -b
        ~/miniconda3/bin/conda init
    - name: Create env
      id: create-env
      run: pip install poetry && poetry install
    - name: Run tests
      id: run-tests
      run: poetry run pytest
