on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    name: A job to test OpenFOAM
    steps:
    - name: Checkout this
      id: checkout-this
      uses: actions/checkout@v2

    - name: Install packages
      id: install-packages
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install -y python3.9 python3-pip openfoam2106-default python3-testresources

    - name: Add GitHub to known hosts
      id: github-knownhosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known-hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install poetry
      id: install-poetry
      run: |
        pip install --user poetry

    - name: Clone paranoodles
      id: clone-paranoodles
      uses: actions/checkout@master
      with:
        name: parallelwindfarms/paranoodles

    - name: Create env
      id: create-env
      run: |
        poetry install -v

    - name: Run tests
      id: run-tests
      run: |
        poetry run pytest
