on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    container: openfoamplus/of_v1906_centos73
    name: A job to test OpenFOAM
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Install tree
      id: tree
      run: yum install -y tree
    - name: Take a look
      id: look
      run: tree -L 2
    - name: Install Miniconda
      id: install-miniconda
      run: wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh && sh Miniconda3-py39_4.9.2-Linux-x86_64.sh -b
    - name: Create conda environment
      id: create-environment
      run: source ~/miniconda3/etc/profile.d/conda.sh && conda env create --name envname --file=environments.yml
    - name: Use OpenFOAM
      id: openfoam
      run: ./run.sh